sudo: false
language: python
python:
 - "3.3"
 - "3.4"
env:
  global:
  matrix:
install:
 - pip install -r requirements.txt
 - pip install coverage
branches:
 only:
  - master
script:
 - python manage.py makemigrations
 - rm __init__.py
 - coverage run manage.py test
matrix:
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
