sudo: true
language: python
python:
 - "3.3"
 - "3.4"
env:
  global:
  matrix:
install:
 - sudo apt-get update
 - sudo apt-get install -y libav-tools libmp3lame0 libavcodec-extra-*
 - pip install -r requirements.txt
 - pip install coverage
 - python manage.py makemigrations
branches:
 only:
  - master
script:
 - rm __init__.py
 - coverage run --source=臺灣言語平臺 manage.py test
matrix:
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
