sudo: true
language: python
python:
 - "3.4"
env:
  global:
  matrix:
install:
 - sudo apt-get update
 - sudo apt-get install -y libav-tools libmp3lame0 libavcodec-extra-*
 - pip install -r requirements.txt
 - pip install coverage
 - pip install flake8
branches:
 only:
  - master
script:
 - coverage run --source=臺灣言語平臺 manage.py test
 - flake8 --exclude=venv,migrations .
matrix:
after_success:
  - coverage report
  - pip install python-coveralls
  - coveralls
