sudo: false
language: python
python:
 - "3.4"
 - "3.5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - python3-dev
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev
      - libboost-all-dev
      - libyaml-dev
      - libxslt1-dev
      - libav-tools  
      - libmp3lame0
      - libavcodec-extra-53
install:
 - pip install flake8
 - pip install python-coveralls
branches:
 only:
  - master
script:
 - pip install .
 - coverage run --source=臺灣言語平臺 manage.py test
 - flake8 --exclude=venv,migrations .
matrix:
after_success:
  - coverage report
  - coveralls
